import fastapi
from llm import LanguageModel

# Create a FastAPI app instance
app = fastapi.FastAPI()

# Initialize a LanguageModel instance
model = LanguageModel()


@app.get("/question")
def question(question: str) -> dict:
    """
    Answer a question.

    Args:
        question (str): The input question to be answered.

    Returns:
        dict: A dictionary containing the answer generated by the language model.
    """
    answer = model.ask(question)
    return {"answer": answer}


if __name__ == "__main__":
    # Run the FastAPI app
    app.run()
